language: python

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=docs2
    - TOXENV=docs3
    - TOXENV=pep8
    - TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
