name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    name: "${{ matrix.tox-env }}  (Python ${{ matrix.python-version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox-env: "py310"
            python-version: "3.10"
          - tox-env: "py311"
            python-version: "3.11"
          - tox-env: "py312"
            python-version: "3.12"
          - tox-env: "py313"
            python-version: "3.13"
          - tox-env: "py314"
            python-version: "3.14"
          - tox-env: "pypy3"
            python-version: "pypy-3.11"
          - tox-env: "coverage"
            python-version: "3.11"
          - tox-env: "pre-commit"
            python-version: "3.11"
          - tox-env: "lint"
            python-version: "3.11"
          - tox-env: "docs"
            python-version: "3.11"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Run tests for ${{ matrix.tox-env }}
        run: tox -e ${{ matrix.tox-env }}
      - name: "Report to coveralls"
        if: matrix.tox-env == 'coverage'
        run: |
          pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
